### ISSUE TITLE
EA Filterable gallery lightbox not working correctly

### ISSUE THREAD

**Issue by Naderi9** [WPDevelopers/essential-addons-for-elementor-lite#438]
The lightbox mode of EA Filterable gallery not filtering the images but instead showing all images!!! 
is there any solution?

**Comment by sabuz** [comment]
Can you please share your site url so that we can inspect?

**Comment by lordeko** [comment]
was asking the same question, actually you can see this behavior in demos https://essential-addons.com/elementor/filterable-gallery/
If I filter the galley i would expect to have the lightbox filtered as well

**Comment by lordeko** [comment]
https://stackoverflow.com/questions/39057637/isotope-and-lightbox-how-to-only-show-the-visible-filtered-images-in-lightbox

maybe this can be useful

**Comment by IftekharPial** [comment]
Hello there @lordeko & @Naderi9 

Hope you are doing well. Sorry for the delayed response.

You will be glad to know that we have introduced Filtering support to the Lightbox gallery items in EA Filterable Gallery.

Please update to the latest version **v5.8.6** to get access to the feature.

Note: Please Regenerate the asset after updating to the latest version
To regenerate assets, you can go to wp-admin -> Essential Addons then, switch to the ‘Tools’ tab and hit the ‘Regenerate Assets’ button. Check out this screenshot: https://d.pr/i/FuLkYy .If you are using a caching plugin, you need to purge the cache from your plugin option and then deactivate the caching plugin temporally so that the new update could take effect.

Hope it helps
Let me know if you face any issues
Thanks
