### ISSUE TITLE
Loading issue

### ISSUE THREAD

**Issue by mkjain1911** [WPDevelopers/essential-addons-for-elementor-lite#502]
Today, Elementor has loading issues with this plugin activated. Any fixes?

**Comment by khan-rafin-ahmed** [comment]
@mkjain1911,

Hi there,

Well, the 'Elementor getting Stuck' error is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://prnt.sc/le9poi

You can install this following plugin on your website to take care of this: https://d.pr/f/D3Dik2

If that doesn't work, make sure to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Let me know how it goes. Thank you!

**Comment by mkjain1911** [comment]
Hey,

So I had done all that trouble shooting before posting it as an issue here.  I have found a temporary fix just now.  If i disable all from the global settings and only activate the 3-4 widgets i am using, it is  working (advanced tabs, pricing table and flip box).  Probably, there conflict with one of the remaining widgets.
