### ISSUE TITLE
Filterable Gallery lightbox buttons tripple click

### ISSUE THREAD

**Issue by Geogagdi** [WPDevelopers/essential-addons-for-elementor-lite#533]
When I'm using lightbox in filterable gallery it loads correctly but when I am trying to switch between images ( using screen arrows) i must click 3 times in the arrow to switch the image it is very couterintuitive and I would be glad if you would change that for single click

**Comment by abid112** [comment]
Hi @Geogagdi , The issue you mentioned is actually fixed earlier in the Essential Addons for Elementor. Make sure you're using latest version(4.1.1) of Essential Addons for Elementor.

Also please regenerate assets from wp-admin -> Essential Addons then, switch to the ‘Tools’ tab and hit the ‘Regenerate Assets’ button. Check out this screenshot: https://prnt.sc/pvozsx

And make sure to Regenerate Files from wp-admin -> Elementor -> Tools as well. 

Then, check back.
If the issue still there, Please share your page URL, So that I can check.

Thank you.

**Comment by Geogagdi** [comment]
thanks it worked
