### ISSUE TITLE
Elementor stops working after creating Feature List

### ISSUE THREAD

**Issue by theseedsowerz** [WPDevelopers/essential-addons-for-elementor-lite#535]
Elementor stops working when I add a feature list to this page: https://whatwherewhen.events/about/ 
I started in safe mode and deactivated plugins but the problem still persists. Elementor works on other pages.

**Comment by abid112** [comment]
Hi @theseedsowerz ,

I believe this is due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://prnt.sc/le9poi

You can install this following plugin on your website to take care of this: https://d.pr/f/D3Dik2

If that doesn't work, make sure to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Let me know how it goes. Thank you!
