### ISSUE TITLE
Loading Issue

### ISSUE THREAD

**Issue by YusufS44** [WPDevelopers/essential-addons-for-elementor-lite#541]
elementor - Essential Addons pro is not loading when I want to edit a page.

**Comment by abid112** [comment]
Hi @YusufS44 ,

As you mentioned that Essential Addons Pro is not loading, So I'm assuming that you're facing 'Elementor getting Stuck' or stuck in the loading spin just like that: https://d.pr/i/0MnPW7

Well this is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://prnt.sc/le9poi

You can install this following plugin on your website to take care of this: https://d.pr/f/D3Dik2

If that doesn't work, make sure to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Let me know how it goes. Thank you!
