### ISSUE TITLE
Click to insert or edit links, add media, add tags did not respond in WordPress background 

### ISSUE THREAD

**Issue by shiianjun** [WPDevelopers/essential-addons-for-elementor-lite#545]

**Comment by abid112** [comment]
Hi @shiianjun ,

In which widget you got this issue actually? I just tried this on the Content Timeline widget where I didn't face this kind of issue. 
Have a look: https://d.pr/i/kD29Ao

So, Can you please tell the me the widget name where you facing this issue so that I can tried that particular widget on my end. 

Thanks!
