### ISSUE TITLE
EA Interfering with Elementor

### ISSUE THREAD

**Issue by mayarshaath** [WPDevelopers/essential-addons-for-elementor-lite#554]
Essential Addons is making Elementor not work. When I try editing a post with Elementor, it just stays on the loading page and never works. I tried deactivating some plugins, and it worked only when I deactivated EA.

**Comment by abid112** [comment]
Hi @mayarshaath ,

Well, the issue you explained according loading issue in edit page of Elementor, This error is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://prnt.sc/le9poi

You need to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Thank you.
