### ISSUE TITLE
Essential Addons Pro breaks Elementor

### ISSUE THREAD

**Issue by helipilot304** [WPDevelopers/essential-addons-for-elementor-lite#556]
When I activate Essential Addons Pro I am unable to edit any pages with Elementor. Once I deactivate the plugin I can edit normally. 
![essential addons pro activiated](https://user-images.githubusercontent.com/72442420/95188059-2eadfb00-0789-11eb-820b-b998b4b92c86.png)

**Comment by abid112** [comment]
Hi @helipilot304 ,

Well, This unlimited loading/spinning of Elementor panel error is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://prnt.sc/le9poi

You need to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Thank you.

**Comment by helipilot304** [comment]
This did the trick! Thank you so much!
