### ISSUE TITLE
Activated Essential Addons but Elementor editor not working

### ISSUE THREAD

**Issue by icerainlee** [WPDevelopers/essential-addons-for-elementor-lite#557]
Wordpress 5.5.1
Elementor: 3.0.11
Essential Addon: 4.2.4
Theme: Astra 2.5.5

Hi all, I noticed that today the Elementor editor is showing loading and loading,
then I try to deactivate plugin one by one,
finally I found that after i deactivated Essential Addons then the Elementor is working well.

Anyone also facing this issue?

I would really appreciate all the help I can get on this.

Thanks very much in advance.

**Comment by abid112** [comment]
Hi @icerainlee ,

Well, This unlimited loading/spinning of Elementor panel error is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://prnt.sc/le9poi

You need to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Thank you.

**Comment by icerainlee** [comment]
@abid112 , thank you so much! It works!

And I will try to adjust the memory also.
