### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hailstromerprasanna** [WPDevelopers/essential-addons-for-elementor-lite#563]
I'm using elementor for building my website but after enabling the essential addons plugin, I'm unable to operate the edit page as the element section doesn't get loaded.

**Comment by abid112** [comment]
Hi @hailstromerprasanna ,

Well, This  error is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://d.pr/i/WVKfum

You need to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Thank you.
