### ISSUE TITLE
 Essential Addons keep loading

### ISSUE THREAD

**Issue by bill2432** [WPDevelopers/essential-addons-for-elementor-lite#565]
Hi when I activate Essential Addons and try to go to one page on elementor and start working the left bar with elementor stuff keep loading (show a circle and keep loading). If I deactivate the  Essential Addons  elements then I can work just fine without the  Essential Addons on my left elementor builder sidebar dasboard. Also if I deactivate the plugin from wordpress plugin center I do not have problem .Finaly ig I try to activate one of the following plugins I still have the cyrcle keep loading... Please help. 
P.s I use the latest updates and for the wotdpress and for the plugins 
Essential Addons for Elementor
Essential Addons for Elementor - Pro
Premium Addons for Elementor

**Comment by abid112** [comment]
Hi @bill2432 ,

This error is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://d.pr/WVKfum

You need to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Thank you.

**Comment by Sisko212** [comment]
Hi All,
This is same issue i had before to align Essentials Addons pro and free, as discussed here:
https://github.com/WPDevelopers/essential-addons-for-elementor-lite/issues/566

**Comment by bill2432** [comment]
Hi yes it was the memory limit for me I put 512M and all works fine. Thanks
