### ISSUE TITLE
Error Loading Elementor with Filterable Gallery turned on

### ISSUE THREAD

**Issue by meghanlynch** [WPDevelopers/essential-addons-for-elementor-lite#569]
Hello there,

My site is having trouble loading Elementor and I've narrowed down the culprit to the Filterable Gallery widget from the Essential Addons. I first noticed this a couple of days ago but did manage to load Elementor and make edits earlier this morning. However, now the same issue appears to be happening again. 

I have the free Elementor Version 3.0.13 and Essential Addons Version 4.3.5. I just updated my WordPress to 5.5.3 hoping that might resolve the issue but I am still having trouble. Do you have any ideas on how to resolve this? I appreciate your advice in advance—thank you!

**Comment by khan-rafin-ahmed** [comment]
@meghanlynch,

Well, the 'Elementor getting Stuck' error is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://prnt.sc/le9poi

You need to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

Let me know if this solves your issue or not. 

Thank you.
