### ISSUE TITLE
Essential Addons Makes Elementor Pro Settings Bar Load Forever.

### ISSUE THREAD

**Issue by CarsonMarain** [WPDevelopers/essential-addons-for-elementor-lite#574]
Hi there Essential Addons team.

I have just started working on a new website and I have everything on it updated to the full versions (See below message).
I have sourced the issue to your plugin (Essential Addons for Elementor Lite).

So far the settings panel on the left when I go to edit a page or post is taking forever to load.

Please let me know if this is an on going issue and you have identified this.
ATM I am going to disable the plugin on this new site but I hope this isn't a issue because we have this plugin on multiple sites already.

If you would like me to get back to you with more investigation, please let me know. I can always update some other staging sites we own and see what happens with them (It might just be this site).

Many thanks,
Carson.

Elementor Version: 3.0.13
Elementor Pro Version: 3.0.6
Addons Version: 1.0.21

(Full List of plugins)
Advanced Database Cleaner
Version 3.0.3

Advanced noCaptcha & invisible Captcha
Version 6.1.5 
	
Akismet Anti-Spam > **DISABLED**
Version 4.1.7 

Astra Pro
Version 2.7.1 

BackupBuddy
Version 8.6.1.

Better Search Replace
Version 1.3.3 

Coming Soon & Maintenance Mode PRO
Version 6.16 

Disable Gutenberg
Version 2.3 

Easy HTTPS (SSL) Redirection > **DISABLED**
Version 1.9.1 

Easy Smooth Scroll Links > **DISABLED**
Version 2.21 

Elementor
Version 3.0.13 

Elementor Pro
Version 3.0.

ElementsKit Lite > **DISABLED**
Version 2.0.9.

Email Address Encoder
Version 1.0.21 

Essential Addons for Elementor
Version 4.3.6 

Google Analytics for WordPress by MonsterInsights > **DISABLED**
Version 7.13.0 

Hello Dolly > DISABLED
Version 1.7.2 

Image Hover Effects - Elementor Addon
Version 1.3.1 

Make Column Clickable Elementor
Version 1.3.1 

P3 (Plugin Performance Profiler) > **DISABLED**
Version 1.5.4 

Really Simple SSL
Version 3.3.5
	
Redirection > **DISABLED**
Version 4.9.2 
	
Simple History
Version 2.37.2 

Smush > **DISABLED**
Version 3.7.2 

Wordfence Security
Version 7.4.12 

WordPress Importer > **DISABLED**
Version 0.7 

WP Fastest Cache > **DISABLED**
Version 0.9.1.2 

Yoast SEO
Version 15.2.1

**Comment by abid112** [comment]
Hi @CarsonMarain ,

Well, This loading error is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://d.pr/WVKfum

You can install this following plugin on your website to take care of this: https://d.pr/f/D3Dik2

If that doesn't work, make sure to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code: 

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory. 

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements. 

Let me know how it goes. Thank you!
