### ISSUE TITLE
Problem with elementor

### ISSUE THREAD

**Issue by hamzakarcic** [WPDevelopers/essential-addons-for-elementor-lite#579]
Dear,

There is problem with essential addons and elementor working together. Im getting endless loading of widgets in elementor when I activate plugin essential addons. In the other way when I deactivate, elementor is working fine.
Hope you will get it fixed.

Best regards!

**Comment by abid112** [comment]
Hi @hamzakarcic ,

Since you closed this issue, I hope you were able to solve this issue. This loading error is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://d.pr/WVKfum

If you face this future again, You can install this following plugin on your website to take care of this: https://d.pr/f/D3Dik2

If that doesn't work, make sure to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Thank you!

**Comment by hamzakarcic** [comment]
Hi Abid,

Thanks for help. I found that on some of earlier post and that solved my problem.

Best regards!


[cid:image001.png@01D6C15A.1308F5A0]
Hamza Karčić
Web developer | Digital marketing manager
+387 62 525 812<tel:+387%2062%20525%20812>
ham.za.karcic@hotmail.com<mailto:ham.za.karcic@hotmail.com>
www.hamzakarcic.tk<https://www.hamzakarcic.tk/>
