### ISSUE TITLE
Essential addons prevents Elementor from loading

### ISSUE THREAD

**Issue by Skinki** [WPDevelopers/essential-addons-for-elementor-lite#588]
Left panel with tools show a wheel spinning in loop. The panel doesn't open ad it's impossibile to use elementor.

**Comment by abid112** [comment]
Hi there,

This loading loop error is generally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://d.pr/WVKfum

If you face this future again, You can install the following plugin on your website to take care of this: https://d.pr/f/D3Dik2

If that doesn't work, make sure to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Thank you!

**Comment by Skinki** [comment]
Thanks a lot! Problem fixed!
Davide
