### ISSUE TITLE
I can't load Pro within Elementor Pro

### ISSUE THREAD

**Issue by netinstinct** [WPDevelopers/essential-addons-for-elementor-lite#591]
Hello,
I just finally installed the plugin and it is not loading my Elementor Page in editor mode. I deactivated the Pro plugin and the Elementor page loaded. But once I reactivated the Pro version, it just spins the wheel.

I have 3.0.9 Elementor Pro and 4.2.4 EA. 

Can someone confirm if they are having or had the same problem and know of the fix?

Thank you. Adam

**Comment by abid112** [comment]
Hi @netinstinct ,

Well, This loading error is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://d.pr/WVKfum

You can install the following plugin on your website to take care of this: https://d.pr/f/D3Dik2

If that doesn't work, make sure to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Let me know how it goes. Thank you!
