### ISSUE TITLE
Elementor hangs up

### ISSUE THREAD

**Issue by rajibdas88** [WPDevelopers/essential-addons-for-elementor-lite#601]
I am using elementor free version and these plugin crashes the elementor. If i disable the plugin elementor works fine but as i active the plugin and use the tools from these plugin and update the page or refresh the page then either elementor or page gets crashed.

**Comment by FariaAarin** [comment]
Hi @rajibdas88 ,

Sorry for the inconvenience caused. Well, the error is normally caused due to a website having low memory. You can check your memory limit by navigating to **wp-admin -> Elementor -> System Info.** Check out this screenshot: https://d.pr/i/a9YFRv

You need to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

**define('WP_MEMORY_LIMIT', '512M');**

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

Let me know if this solves your issue or not. If it doesn't, you can check for plugin conflicts by deactivating all the plugins except for Elementor and Essential Addons.

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Thank you.
