### ISSUE TITLE
Issue with 'load more' button in Product Grid

### ISSUE THREAD

**Issue by ClaseVIvas** [WPDevelopers/essential-addons-for-elementor-lite#606]
Hello community.

I have a problem with the plugin in Elementor Pro.
I have a page with two languages: Spanish and Galician.

The problem is that the button 'load more products' when clicking on the exit 'loading ...' instead of putting it in the configured language.

I have 'Loco translate' and I have entered the text string and modified the 'loading ...' to 'Loading ...'.
In Spanish he does it perfectly.
But in Galician it is not configured as I want. Keeps the 'loading ...'

This is the web:
[https://tonyson.es](url)

Could you help me please?

**Comment by FariaAarin** [comment]
Hello @ClaseVIvas 

Sorry for the inconvenience caused.  Could you please share with us a screenshot of the configuration? 

Meanwhile, I would like to request you to create a support ticket [ here]( https://wpdeveloper.net/support/my-tickets/) so that we can check the issue from our end and solve it as soon as possible.

Thank you.

**Comment by FariaAarin** [comment]
Hi @ClaseVIvas 

Hope you're doing well. Can you please update us regarding your issue?L ooking forward to hearing from you.

Thank you.
