### ISSUE TITLE
elementor is not loading, i cant use it now. really bad experience. please help!

### ISSUE THREAD

**Issue by harshdeepkumar** [WPDevelopers/essential-addons-for-elementor-lite#608]

**Comment by FariaAarin** [comment]
Hello @harshdeepkumar,

I am sorry about the difficulty you've encountered so far. Actually, This issue is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://prnt.sc/le9poi

You need to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file. Please place the code just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

Let me know if this solves your issue or not. If it doesn't, you can check for plugin conflicts by deactivating all the plugins except for Elementor and Essential Addons.

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Hope this will help.

Thank you.

**Comment by harshdeepkumar** [comment]
Thanks for your reply. I tried this thing as you said but it's still
not working, is there any other way, because i won't be able to proceed
with my work if this isn't resolved.

**Comment by FariaAarin** [comment]
Hi,

Can you please check for plugin conflicts by deactivating all the plugin except for Elementor and Essential Addons. if you've already tried this method and still didn't work please create a support ticket with the temporary login access so that we can have a look into the issue and solve it.

You can also create a support ticket through this link: https://wpdeveloper.net/support/my-tickets/

Thank you.
