### ISSUE TITLE
EA Google map: something went wrong

### ISSUE THREAD

**Issue by edikaufmann** [WPDevelopers/essential-addons-for-elementor-lite#612]
when using 'EA Google map' - using lat / long - I get an error:
Console: see attached .log
![Gm versions](https://user-images.githubusercontent.com/51043011/109925341-e7894f00-7cc1-11eb-9dca-b1d2691ef18b.png)
[Gm console.log](https://github.com/WPDevelopers/essential-addons-for-elementor-lite/files/6081552/Gm.console.log)
![Gm something](https://user-images.githubusercontent.com/51043011/109925349-e9531280-7cc1-11eb-9efe-b246c6679967.png)

I see the map flashing up for 1 second and then get screen: Something went wrong ... (see attached 'Gm something.png')

In 'Essential addons' in 'settings' I set the Google 'API key'!
PS: The standard Google map (non-EA, using an address) the map shows correct! BUT I need lat / long!

My Elementor versions: see 'gm versions.png'

thanks for your time - I can't see what I'm doing wrong!
ed kaufmann

**Comment by FariaAarin** [comment]
Hi @edikaufmann ,

Extremely sorry for the inconvenience caused. Actually, The reason that you're facing this issue is because the API key request limit is over for the Google Map platform. Since Google Map is a Paid Platform, you need to purchase your API plan from Google Map Platform from here: https://cloud.google.com/maps-platform/pricing

Hope you understand.

Thank you.
