### ISSUE TITLE
Problem with Advance Accordion 

### ISSUE THREAD

**Issue by vick1ye** [WPDevelopers/essential-addons-for-elementor-lite#613]
Hi there, I have some problem with Advance Accordion in essential-addons-for-elementor, which is unreadable for reason unknown.  The accordion wouldn't expand after clicked, but still allow to edit under edit mode.
website: https://denzoleather.com/product/repeto/

![1614842852(1)](https://user-images.githubusercontent.com/80028874/109926824-5edcd400-7cfe-11eb-8b9a-90c3cfe5aeb9.png)
![1614842927(1)](https://user-images.githubusercontent.com/80028874/109926834-61d7c480-7cfe-11eb-9f9d-ef97787fd7cf.png)

**Comment by FariaAarin** [comment]
Hello @vick1ye ,

Hope you're doing well. This issue is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://d.pr/i/MHHWa8

You can install the following plugin on your website to take care of this: https://d.pr/f/D3Dik2

If that doesn't work, make sure to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Let me know how it goes. Thank you!
