### ISSUE TITLE
'Duplicator' extension does not correctly duplicate Events Manager plugin events

### ISSUE THREAD

**Issue by mwittmann** [WPDevelopers/essential-addons-for-elementor-lite#614]
The 'Duplicator' extension does not correctly duplicate [Events Manager plugin](https://wordpress.org/plugins/events-manager/) events. In fact, it corrupts the event information for events that have registration enabled and tickets defined. I think it's quite dangerous that the 'Duplicator' is enabled for ALL post types by default... It may also fail on other custom post types.

It's also a problem that you can only select 'All' or just one single post type for 'Duplicator' to work with. It would be better if it allowed multi-selection of the post types. Then I could enable it just for standard post types (Page and Post).

**Comment by abid112** [comment]
Hi @mwittmann ,

Well, Duplicator extension perfectly works with generic Pages and Posts actually.
Generally, all Duplicator plugins work like this.  Since 3rd party plugins have some their own meta field, It cant be captured with the Duplicator extension.

However, thanks for your awesome idea according to select Post Type from the setting. This will help us to improve our plugin in the future.

Thank you and have a good day!

**Comment by mwittmann** [comment]
I just want to reiterate my concern. Since the EA Duplicator provides a "duplicate" link for **all** post types **by default**, it makes it very easy for an unaware WordPress editor to try to duplicate a custom post type that EA Duplicator **cannot duplicate correctly**, and that may lead to **serious database corruption**. In the case with the Events post type from the Events Manager plugin, it does lead to serious database issues which took me many hours to clean up, and even then there was some data loss I could not recover.

It would be far better if, by default, the EA Duplicator showed it's "duplicate" link **only for standard WordPress post types or for "known good" post types from other plugins**. It should allow additional post types to be **selected and added individually**, and should probably display some **cautionary text** that compatibility with all custom post types cannot be guaranteed. In addition, it would be wise for you to **disallow** selecting post types that are **known not to work**, such as for Events Manager. (You could sniff and detect the plugin along with its custom post type.)

The users of Elementor and your EA Addons simply expect things to work correctly for professionally developed components. It will cause a lot of user distrust and unhappiness if your plugin destroys their data. I would think you would not want to risk that.

**Comment by mwittmann** [comment]
I see this was closed but with no indication of whether this has been resolved, or is on the roadmap to be resolved. I'll just reiterate that it is dangerous for EA Duplicator to be enabled to duplicate all custom post types by default. This risks database corruption (and is proven to produce database corruption for Events Manager events). EA Duplicator should default to only be available to duplicate "known good" post types by default, which would include all standard WP post types.

**Comment by abid112** [comment]
Hi @mwittmann ,

Well, I've mentioned in my previous response that 3rd party plugins have their own meta fields, It can't be captured with the Duplicator extension. Basically, it needs to give support for each 3rd party plugins for their own meta fields which doesn't make sense since it depends on the plugin authors and developers defined meta fields name.

I would recommend you to uncheck for your Event Managers post type if it doesn't suit with Event Managers plugin. EA Duplicator is working fine for the native WordPress Pages, Posts, and Custom Post Type(where no extra metadata exists).

Thank you!

**Comment by mwittmann** [comment]
Hello Abid,

I cannot "uncheck" only the Event custom post type. The EA Duplicator "Select Post Types" configuration setting is (still) a single-select dropdown combo box. In other words, it only allows you to select "ALL" or a single post type. See the screenshot below.

The problem is that it defaults to "ALL", which is *not safe*, as I've noted earlier in this thread.

If you were to make the "Select Post Types" dropdown multi-select, then I recommend its default setting should be _only_ the standard WordPress post types. 

![image](https://user-images.githubusercontent.com/5827956/135148732-b7f8c7ea-d66e-4ec7-9504-151b71382ced.png)

Thanks!
