### ISSUE TITLE
Error Essential Addons y Elementor PRO

### ISSUE THREAD

**Issue by dfuentes911** [WPDevelopers/essential-addons-for-elementor-lite#617]
Se presenta un error al tener activado elementor pro y Essential Addons, no cargan los bloques, se queda cargando y no aparecen para poderlos usar en el maquetador.

**Comment by FariaAarin** [comment]
Hi @dfuentes911,

Extremely sorry for the inconvenience caused. Actually, the error is normally caused due to a website having low memory. You can check your memory limit by navigating to **wp-admin -> Elementor -> System Info.** 
Check out this screenshot: https://d.pr/i/a9YFRv

You need to increase the memory limit. To increase the memory limit you will have to modify the **wp-config.php** file of yours. Just above this line **" /* That's all, stop editing! Happy blogging. */"** add this following line of code:

**define('WP_MEMORY_LIMIT', '512M');**

You would find the **wp-config.php** file under your WordPress directory.

You can also read this blog to modify the **wp-config.php** file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

Let me know if this solves your issue or not. If it doesn't, you can check for plugin conflicts by deactivating all the plugins except for Elementor and Essential Addons.

Hope this will help you.

Thank you.
