### ISSUE TITLE
Most pages will not show any elements below the first one or videos at all across all pages

### ISSUE THREAD

**Issue by WalrusSlayer** [WPDevelopers/essential-addons-for-elementor-lite#618]
**Example of webpages that work:**
https://mcvantage.us/creative/
https://mcvantage.us/command-guide/

**Example of webpages that do not work:**
https://mcvantage.us/worldedit/
https://mcvantage.us/connect/

I've tested with various themes. I have contacted my host (BlueHost), WordPress, the theme developers (Sydney), enabled and disabled plugins, and have found that it is an Elementor issue. It randomly began sometime this month and I have been non-stop trying to no avail to fix it, which now leads me to believe it is a bug.

If you need further information please contact me!

Thanks for your time.

**Comment by abid112** [comment]
Hi @WalrusSlayer ,

Hope you're doing good.
I went through your website and looked over all the pages that you gave. I didn't find any EA Elements on your page.
Can you please confirm that you're using Essential Addons for Elementor and facing any issue with this?

I deeply checked on your page by searching `eael` from the browser inspector but I didn't find any  EA widgets actually. If the white page issue comes from the EA elements, It still should print the markup actually.

However, If you're using the Essential Addons and this issue comes from the Essential Addons, then please create a support ticket with temporary admin access from here: https://wpdeveloper.net/support/new-ticket/

Our Support Team will get back to you and deeply check this issue for you.
Thank you!
