### ISSUE TITLE
Not loading elementor widget due to essential addons for elementor.. please update

### ISSUE THREAD

**Issue by sachin-loop** [WPDevelopers/essential-addons-for-elementor-lite#619]
Not loading elementor widget due to essential addons for elementor , after deactivating essential addons the elementor widget works properly and also it slow down the admin area. please update it soon

**Comment by abid112** [comment]
Hi @sachin-loop ,

This error is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://d.pr/WVKfum

You need to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

**define('WP_MEMORY_LIMIT', '512M');**

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Thank you.
