### ISSUE TITLE
Keeping Elementor in constant load

### ISSUE THREAD

**Issue by 8WiaM8** [WPDevelopers/essential-addons-for-elementor-lite#622]
When I activate the plug-in, elementor stops working. It sets elementor in a constant load, but never finishes loading no matter how long I wait. To be more clear: the widget menu is what keeps on loading.

**Comment by GerardPerret** [comment]
Hi,
had the same and this is related to Wordfence plugin used with EA.
Found this topic related to anothe addon and this is fixing the issue by Increasing PHP Memory Limit & Maximum Execution Time.
https://premiumaddons.com/docs/im-getting-a-blank-page-on-elementor-after-activating-premium-add-ons/
Anyway I have added a bug report here.
Regards

**Comment by FariaAarin** [comment]
Hi there,

Well, the error is normally caused due to a website having low memory. You can check your memory limit by navigating to **wp-admin -> Elementor -> System Info.** Check out this screenshot: https://d.pr/WVKfum

You can install the following plugin on your website to take care of this: https://d.pr/f/D3Dik2

If that doesn't work, make sure to increase the memory limit. To increase the memory limit you will have to modify the **wp-config.php** file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */ " add this following line of code:

**define('WP_MEMORY_LIMIT', '512M');**

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Hope this will solve your issue. Let me know how it goes.

Thank you!

**Comment by GerardPerret** [comment]
Very clear, thank you
   
  
  
   
    Le 28/03/2021 11:12, FariaAarin ***@***.***> a écrit :
   
   
    
   
   
    
   
   
   Hi there,
   Well, the error is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://d.pr/WVKfum
   You can install the following plugin on your website to take care of this: https://d.pr/f/D3Dik2
   If that doesn't work, make sure to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */ " add this following line of code:
   define('WP_MEMORY_LIMIT', '512M');
   You would find the wp-config.php file under your WordPress directory.
   You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/
   If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.
   Hope this will solve your issue. Let me know how it goes.
   Thank you!
   —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
  
  
   
  
  
    Best Regards/Cordialement 
   Gérard PERRET | GPITS  | Cell + 33 6 08 87 73 06 | ***@***.***| www.gpits.fr
