### ISSUE TITLE
Caregories query for EA Smart post list doesn’t work 

### ISSUE THREAD

**Issue by Alvindu13** [WPDevelopers/essential-addons-for-elementor-lite#626]
Hello ! 

First, Thank you a lot for that you do. 
It’s seems the categories query of the EA Smart Post List doesn’t work. Nothing post are found when We charge a new categories 

i will add some pictures this week-end to complete the  issue

**Comment by FariaAarin** [comment]
Hi there,
Hope you're doing well. I've checked from my end and it seems to be working fine. Please have a look: https://d.pr/v/5xmnXn

Can you please share your website URL so that we can check from our end? However, It seems a plugin conflict issue. Please do a plugin conflict test. To do so deactivating all the third-party plugins one by one except for Elementor and Essential Addons and recheck. Check this out for more details: https://essential-addons.com/elementor/docs/plugin-conflicts-wordpress-website/

Let me know how it goes. 

Thank you.
