### ISSUE TITLE
carregamento infinito do elementor

### ISSUE THREAD

**Issue by marjorieesp** [WPDevelopers/essential-addons-for-elementor-lite#629]
Toda vez que ativo o pugin para utilizar o recurso PRO o elementor para de funcionar. O plugin está atualizado.

**Comment by olairmarcos** [comment]
Olá descobri que ao desativar os elementos do woocommerce o elementor volta a trabalhar normal. Pode ajudar até o plugir ser atualizado.
Product Grid
Woo Product Collections
Woo Product Carousel
Woo Checkout
Woo Product Compare

**Comment by abid112** [comment]
Hi @marjorieesp @olairmarcos ,

This error is normally caused due to a website having low memory. You can check your memory limit by navigating to **wp-admin -> Elementor -> System Info**. Check out this screenshot: https://d.pr/WVKfum

You need to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Thank you.
