### ISSUE TITLE
Woocommerce widget crashes elementor page builder

### ISSUE THREAD

**Issue by olairmarcos** [WPDevelopers/essential-addons-for-elementor-lite#630]
Woocommerce widget crashes elementor page builder

When we activate the elements of woocommerce in Essential Addons it causes the elementor page builder to stop. When deactivating the widgets of the woocomerce, the elementor returns to normal working.
WooCommerce Elements

Product Grid
Woo Product Collections
Woo Product Carousel
Woo Checkout
Woo Product Compare

Wordpress 5.7
PHP 7.4
Dbase Maria db 10.4
Woocommerce 5.1.0
Essential Addons

Thanks for help

**Comment by rasel-wp** [comment]
Hi @olairmarcos,

Sorry for the inconvenience caused. Can you please share a screenshot that what error you are getting on your side? So that we can check and help you to fix the issue.

In the meantime, please make sure that you are using updated versions of Essential Addons on your website. The current version of Essential Addons Free 4.6.0 and Essential Addons PRO 4.3.5 (if available) on your website.

Let me know the update. Thanks!

**Comment by rasel-wp** [comment]
Hi @olairmarcos,

We had already fixed the above issue. Is your issue fixed with the latest version of Essential Addons? Let us know.

If still, you are facing any issues, you can create a support ticket here: https://wpdeveloper.net/support/new-ticket with details.
Our support team will get back to you very soon.

Thanks!
