### ISSUE TITLE
Essential Addon Conflicts with Elementor

### ISSUE THREAD

**Issue by Brian-Doan** [WPDevelopers/essential-addons-for-elementor-lite#631]
I installed the latest versions for both Elementor and EA, but it seems that EA prevents Elementor from working in the edit mode. I read a lot of instructions and they all mentioned the memory limit problem. But I'm sure that my WP site has 512M of memory limit. I also tried to rollback both of them but still no work.

**Comment by FariaAarin** [comment]
Hi @Brian-Doan,

I'm sorry to hear that you're facing this issue. Since your issue has not been solved after increasing the memory. I would like to request you to enable debug log and check for plugin conflicts. 

To enable debug log to your cPanel or FTP server. Open the **‘wp-config.php’** from the WordPress Directory. Then, simply just add the following code just above **/* That’s all, stop editing! Happy blogging. */ :**

 **define('WP_DEBUG', true);** 

You can check for Plugin conflicts by deactivating all the third-party plugins one by one except for Elementor and Essential Addons. Simply go to your WordPress Dashboard and navigate to **wp-admin -> Plugins** and then, deactivate other Plugins.

Let me know if it works. If the issue still persist I would like to request you to create a ticket [here](https://wpdeveloper.net/support/my-tickets/) with your website temporary access so that we can have a look into the issue and resolve this.

Thank you.

**Comment by Brian-Doan** [comment]
I did add the code to 'wp-config.php'. I also deactivated all the third-party plugins and active them again one by one. Now I know the problem is among EA, WooCommerce, and some plugins relevant to WooCommerce like Wishlist or Variation Swatches, but I'm not sure it comes from which one. I cannot find any document about this issue.
Please help!

**Comment by FariaAarin** [comment]
Hi @Brian-Doan,

Thank you for your detailed information. I would like to request you to create a support ticket **[here](https://wpdeveloper.net/support/my-tickets/)** so that we can investigate the issue deeply and resolve this. 

Thank you.

**Comment by Inhousedm** [comment]
im having the same issue!!
