### ISSUE TITLE
issues with loading 

### ISSUE THREAD

**Issue by vrmnihal** [WPDevelopers/essential-addons-for-elementor-lite#639]
As it has new update after that it become the worst with elementor wihich it has some issues with elementor loading... 
i would like to say kindly do fix this issues as soon as possible

**Comment by abid112** [comment]
Hi @vrmnihal ,

I'm really sorry to hear that you're facing Elementor Stuck/Loading issue on your end
It should not be for the new update. 

This error is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://d.pr/WVKfum

You need to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Thank you.
