### ISSUE TITLE
Does not respond with elementor pro

### ISSUE THREAD

**Issue by Inhousedm** [WPDevelopers/essential-addons-for-elementor-lite#650]
When the plugin is active, elementor widget panel does not load. See screenshot. Please fix ASAP
![image](https://user-images.githubusercontent.com/84234000/118362085-568ff780-b5d1-11eb-8176-4667eea8c392.png)

**Comment by rasel-wp** [comment]
Hi there,

Sorry for the inconvenience caused. Well, the 'Elementor getting Stuck' error is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://d.pr/WVKfum

You can install the following plugin on your website to take care of this: https://d.pr/f/D3Dik2

If that doesn't work, make sure to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Let me know how it goes. Thank you!
