### ISSUE TITLE
Essential elementor free do not allow elementor and elementor pro to load

### ISSUE THREAD

**Issue by mondemaya** [WPDevelopers/essential-addons-for-elementor-lite#663]
First issue: Elementor editor load but there is a infinite loading in elementor options
Second issue: when the first issue do not happen, the entire elementor editor do not load. This happens only when essential elementor is active.
![ddddd](https://user-images.githubusercontent.com/72323620/123526157-30ab4780-d693-11eb-8bc1-870e725946a9.jpg)

**Comment by abid112** [comment]
Hi @mondemaya ,

Sorry for the inconvenience. We're already aware of this issue and our dev team already fixed this issue in one of our dev branch.  This will be fixed in the future version of Essential Addons for Elementor.

For now, You can download this branch to get this resolve: https://github.com/WPDevelopers/essential-addons-for-elementor-lite/tree/1484

Thank you!

**Comment by abid112** [comment]
Hi @mondemaya ,

We've released a new update where we fixed this issue.
So make sure to update **Essential Addons for Elementor** to the latest version on your website to get this resolve.

Thank you!
