### ISSUE TITLE
Elementor PopUp, Gravity Forms + Activated Conditional Logic + EA Gravity form = Form is not shown

### ISSUE THREAD

**Issue by Arndt-** [WPDevelopers/essential-addons-for-elementor-lite#674]
If I try to embed a Gravity Form using your EA GF Widget and the actual form has conditional logic activated the form will not show up on an Elementor PopUp.

**Comment by abid112** [comment]
Hi @Arndt- ,

Thanks for pointing this out to us
I've successfully reproduced this issue on my end aswell. I've informed our dev team according to this. Besides this issue, we're planning to improve/compatible our EA Gravity Form widget with the latest version of Gravity Form.

This will be fixed in the future version don't worry.

Thank you!

**Comment by abid112** [comment]
Hi @Arndt- , 

I just deeply check this issue with our dev team. Actually, this is not related with Essential Addons for Elementor actually.
Gravity Form shortcode [that contain Conditional Logic] neither works on inside the Elementor Popup. Have a look at this video: https://d.pr/v/vpcH79

This is a known issue of Elementor/Gravity Form. Have a look at this: https://github.com/elementor/elementor/issues/7245

Hope you understand.
Thank you!
