### ISSUE TITLE
Plugin not compatible with Elementor

### ISSUE THREAD

**Issue by Skyhightechbh** [WPDevelopers/essential-addons-for-elementor-lite#678]
Hi, 
I'm checking the compatibility of this plugin in elementor and it's showing incompatible.

I'm using the updated version of Essential addons plugin 4.8.3 | 

and have Elementor 3.3.1 and Elementor Pro 3.3.6. 

Everytime I open page to edit the elementor section keeps loading because of this Plugin. 
As soon as I disable it. it starts working

**Comment by abid112** [comment]
Hi @vrmnihal ,

I'm really sorry to hear that you're facing Elementor Stuck/Loading issue on your end
We've already tested our plugin with the latest version of WordPress and Elementor. So incompatible issues should not happen actually!

This error is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://d.pr/WVKfum

You need to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

**define('WP_MEMORY_LIMIT', '512M');**

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Thank you.

**Comment by Skyhightechbh** [comment]
Hi Abid,

 

I tired the method you have and it did work out for me. The Elementor section is now loading and working fine.

 

Thank you for your help!

 

Regards,

 


 <https://www.skyhightech.me/> 


Asim Waqar


Project Manager | SkyHighTech 


 


 +973 3620 7321 |  +973 1650 5112 


 ***@***.*** 

	

 Office No: 203, BNH Tower, Al Seef District 


  <http://www.skyhightech.me/> www.skyhightech.me 


 <https://www.facebook.com/SkyHighTechbh> 


 <https://www.youtube.com/channel/UCS_-2QTWXTgxKYLWH_KZ0sg> 


 


 <https://www.linkedin.com/company/skyhightech> 


 <https://www.instagram.com/skyhightechbh/> 





The content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

**Comment by abid112** [comment]
Hi @Skyhightechbh ,

I am glad I was able to help, please feel free to reach us anytime you need help, we are always here to help. If you don't mind me asking, could you do me a favor, and spend 30-sec to review us following this link, this will help us to serve better. Thank you in advance! Link to review - http://wpdeveloper.net/review-essential-addons-elementor

Thank you.
