### ISSUE TITLE
Unable to save when adding or removing elements from element screen. 

### ISSUE THREAD

**Issue by SupaDigital** [WPDevelopers/essential-addons-for-elementor-lite#691]
Hi

I am unable to save changes made to activate or deactivate elements on the elements screen. I get "Oops, something went wrong" when I click save. 

I am using Elementor (obviously :) ), Astra theme with Astra pro plugin. 

I need to activate the blog post grid element, but am unable to do so. 

Thanks

**Comment by sadmansakibnadvi** [comment]
Well, It seems unusual. Can you please check if there is any plugin conflict or not. In order to do that, please disable all of your plugins one by one except **Elementor and Essential Addons for Elementor**.
Let me know how it goes!

If the issue still persists, I would recommend you to create a support ticket from here: https://wpdeveloper.net/support/
