### ISSUE TITLE
CSS Enqueue Improvement [ WP Rocket RUCSS Compatibility ]

### ISSUE THREAD

**Issue by mehedihasanziku** [WPDevelopers/essential-addons-for-elementor-lite#692]
Hello,

Glad to know that thread available in github.

I see that saved css added using random hash pattern ( id & filename ) in most of the pages

`"wp-content/uploads/essential-addons-elementor/*.min.css"`

that files content looks to me similiar in all pages. now if it's adding random things like that wprocket fails to detect them as single css files in rucss but it's an same request with random pattern . i will request if possible please improve this method to make it one with correct name or please let me know more insights related to this.

Thanks

**Comment by abid112** [comment]
Hi @mehedihasanziku ,

Hope you're doing good.

**Essential Addons** generates the assets as per widget loads on the page hence this file is dynamically generated on this folder actually. We've implemented this in an optimized way. If you want to exclude or do some with the CSS, JS of Essential Addons, you can use the folder(```wp-content/uploads/essential-addons-elementor/```) instead of the files.

Thank you!
