### ISSUE TITLE
Accordion / Tabs not working

### ISSUE THREAD

**Issue by MattHG** [WPDevelopers/essential-addons-for-elementor-lite#696]
Accordion / Tabs not working. They work inside Elementor editor but not on front end of site.

**Comment by amitbarai013** [comment]
Hi @MattHG,

It may happen due to caching issue. Can you please try doing the following: 
To regenerate assets, you can go to wp-admin -> Essential Addons then, switch to the ‘Tools’ tab and hit the ‘Regenerate Assets’ button. Check out this screenshot: https://d.pr/i/OeGVUT

Also, make sure to Regenerate Files from wp-admin -> Elementor -> Tools as well. Check out this screenshot: https://d.pr/i/23N5eb

If the issue still persists, please try clearing your browser cache (by pressing ctrl+shift+R) or try another browser (incognito mode) too.

Let me know how it goes. 
Thank you.
