### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by lucie-pollet** [WPDevelopers/essential-addons-for-elementor-lite#697]
I can't even use elementor because of this plugin, and I can't some of the themes I created...

**Comment by rasel-wp** [comment]
Hi @lucie-pollet,

Sorry for the inconvenience caused. Can you please describe some more about your query that what issue you are facing by using the Essential Addons plugin? You can share a screenshot or screen record for better understanding. So that we can check and help you to fix the issue.

Let me know. Thanks!
