### ISSUE TITLE
I can not use the plugin with the new elementor update

### ISSUE THREAD

**Issue by davidnavus** [WPDevelopers/essential-addons-for-elementor-lite#702]
I have some issues with the add on:

1. I use the add on but when changing a specific product it updates the information for all the product I have created
2. I cannot use the tool today the widgets are not available and I cannot enter Elementor

**Comment by mahbubshovan** [comment]
Hi @davidnavus 

Sorry for the inconvenience caused.
It seems really very strange. I am getting a little bit confused about which widget you are getting the issues. Can you please share a screen record or screenshot for better understanding? So that we can understand and help you to fix the issue.

Let us know the update. Thanks!
