### ISSUE TITLE
the essential addon its give a bug 

### ISSUE THREAD

**Issue by jonaquind** [WPDevelopers/essential-addons-for-elementor-lite#704]
im using this plugin for wordpress and when its active my page star to reload over and over again this didn't happened before but now its happen I just started using yesterday

**Comment by sadmansakibnadvi** [comment]
Hi there,

Well, the 'Elementor getting Stuck' error is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://d.pr/i/a9YFRv

You need to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.com/troubleshoot-preview-loading-error-elementor/

Let me know if this solves your issue or not. If it doesn't, you can check for plugin conflicts by deactivating all the plugins except for Elementor and Essential Addons.

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Thank you.

**Comment by jonaquind** [comment]
thanks its work for now thank u

**Comment by jonaquind** [comment]
sorry but bother but the plugin now is just giving my the problem when I edit I did everything u told me but only work for user  I put the line code a deactivate all my plugins like you told y activate elementor and essential and still happen but only now when I start to edit

**Comment by sadmansakibnadvi** [comment]
Hello there,

Sorry for the inconvenience.

If you are still facing the same problem. Can you please create a support ticket, so that we can check and solve your issue. 
Link to create a support ticket: https://wpdeveloper.com/support/new-ticket

Thank you.
