### ISSUE TITLE
Notice: Undefined offset: 1 in /var/www/wp-content/plugins/essential-addons-for-elementor-lite/includes/Elements/Sticky_Video.php on line 853

### ISSUE THREAD

**Issue by niitiikaa** [WPDevelopers/essential-addons-for-elementor-lite#708]
Notice: Undefined offset: 1 in /var/www/wp-content/plugins/essential-addons-for-elementor-lite/includes/Elements/Sticky_Video.php on line 853
after I attached sticky video element from essential addon
![image](https://user-images.githubusercontent.com/77662431/144552974-58e43126-9216-4054-a742-10910954ab92.png)

**Comment by amitbarai013** [comment]
Hi @niitiikaa ,

Hope you are doing well.


We are really sorry for the inconvenience. We found the issue regarding the **Sticky Video** widget. Our developer team is working on this issue. This will be solved soon.


Thanks.
Have a good day!

**Comment by amitbarai013** [comment]
Hi @niitiikaa ,

Greetings.


We are really happy to inform you that this issue regarding the **Sticky Video** widget has been fixed in our developer version. Please download and install the developer version of Essential Addons from here: https://d.pr/f/xQQeEV


Let me know how it goes. 

Thanks. :)
