### ISSUE TITLE
Facing problems on my website..........need  help

### ISSUE THREAD

**Issue by pyang1123** [WPDevelopers/essential-addons-for-elementor-lite#717]
Hi guys,

I'm building my website using essential addons with elementor on the wordpress.
It run slow and I find something timeout..... please see attachment .
As a layman, I am incapable of solving the problems of the moment.
I Need your help ASAP to fix my website.

Thanks A lot !!

Report link:
https://gtmetrix.com/reports/increasecc.com/AsY6wKlj/

![擷取](https://user-images.githubusercontent.com/91523190/148808539-3e0ee85e-eea4-489b-b047-ba6e2c46f138.PNG)

**Comment by sadmansakibnadvi** [comment]
Hello @pyang1123 ,

Greetings. Hope you are doing well.

Unfortunately it is happening because that particular file isn't found in your server. So it is requesting from the header file and that's why there is the delay. If you are using any caching plugin i would suggest you to deactivate the plugin and can you please try doing this following: To regenerate assets, you can go to wp-admin -> Essential Addons then, switch to the ‘Tools’ tab and hit the ‘Regenerate Assets’ button. Check out this screenshot: https://d.pr/i/iBccDw

Also, make sure to Regenerate Files from wp-admin -> Elementor -> Tools as well. Check out this screenshot: https://d.pr/i/23N5eb
 
 After that please check again from GTmetrics. Let me know how it goes.
Thank you!

**Comment by pyang1123** [comment]
> Hello @pyang1123 ,
> 
> Greetings. Hope you are doing well.
> 
> Unfortunately it is happening because that particular file isn't found in your server. So it is requesting from the header file and that's why there is the delay. If you are using any caching plugin i would suggest you to deactivate the plugin and can you please try doing this following: To regenerate assets, you can go to wp-admin -> Essential Addons then, switch to the ‘Tools’ tab and hit the ‘Regenerate Assets’ button. Check out this screenshot: https://d.pr/i/iBccDw
> 
> Also, make sure to Regenerate Files from wp-admin -> Elementor -> Tools as well. Check out this screenshot: https://d.pr/i/23N5eb
> 
> After that please check again from GTmetrics. Let me know how it goes. Thank you!

**Comment by pyang1123** [comment]
Hi @sadmansakibnadvi ,

Thanks for your reply.
I follow these two steps and the issue still there.
Any suggestion for me ?

The re-test report is below:
https://gtmetrix.com/reports/increasecc.com/80FfofWP/

Thanks A lot !

**Comment by sadmansakibnadvi** [comment]
Hello there,

Can you please create a support ticket with temporary login access from here so that we can check from your end: https://wpdeveloper.com/support/new-ticket

Thank you.

**Comment by pyang1123** [comment]
Hi @sadmansakibnadvi ,

Please see whether the support ticket is available or not.

Thank you.

**Comment by pyang1123** [comment]
Hi @sadmansakibnadvi  ,

The problem has been solved.
Thanks for your support !
