### ISSUE TITLE
Multiple unwanted tags in Call to Action widget

### ISSUE THREAD

**Issue by simonclay** [WPDevelopers/essential-addons-for-elementor-lite#725]
Version 5.1.4:

Problem 1: 
If we drop a Call to Action widget on the page and remove the Title, the widget still outputs an empty tag.

Problem 2:
When we type or paste into the Content area, empty <p> tags are added above and below the new content, with no way to remove them.

![Screenshot 2022-05-30 at 12 15 39](https://user-images.githubusercontent.com/2143351/170982496-f1028723-ab73-4095-b447-b1651461f435.png)
.

**Comment by arrasel13** [comment]
Hi @simonclay,

Sorry for the inconvenience caused. I have checked the issue and am able to reproduce the issue.
For Problem-1: I am forwarding this to our Dev Team. They will check and fix the issue as soon as possible.

And for Problem-2: It seems you have copied and pasted the text or written the text on the **Content > Visual** section (https://d.pr/i/r02hkH). And that's why extra HTML paragraph tags add to the content. For fixing this, please click on the **Content > Text** and click on the text field and then save the settings. And recheck once. It will be ok. You can check this screencast: https://d.pr/v/vt9I3F

And once we have fixed Problem-1 we will inform you. Don't worry. Please allow us time for fixing the issue.

Thanks for your patience!

**Comment by simonclay** [comment]
Hi, thanks very much for such a swift response and for logging with the Dev Team. :)

Thanks too for the Content area workaround.

**Comment by arrasel13** [comment]
Hi @simonclay,

We have already fixed the Problem-1 issue on our Dev version. Please check with this branch: https://github.com/WPDevelopers/essential-addons-for-elementor-lite/tree/2124

And let us know if you are facing any issues.

Thanks!

**Comment by simonclay** [comment]
Amazing thanks. I’ve tested and problem 1 now fixed on 'Call to Actions'.

(I notice those problems are present on other widgets too like: ‘Info Box’, 'Flip box', 'Image Accordion')

**Comment by arrasel13** [comment]
Hi @simonclay,

Thanks for your update. I am checking the other widgets which you mentioned above. We will fix the issue and will inform you. Please allow us time.

Thanks for your findings and patience!

**Comment by arrasel13** [comment]
Hi @simonclay,

Hope you are doing well. We have already fixed the above-mentioned issues.  Please check with this branch: https://github.com/WPDevelopers/essential-addons-for-elementor-lite/tree/2124

And let us know if you are facing any issues.

Thanks!

**Comment by robinwpdeveloper** [comment]
Fix is **released** in EA 5.1.5 (14 June, 2022).
Closing this issue.

Feel free to reopen if you still have the issue with the latest version (5.6.0).
