### ISSUE TITLE
"row::" & "col::" bug when editing DataTable

### ISSUE THREAD

**Issue by nxmndr** [WPDevelopers/essential-addons-for-elementor-lite#735]
Hi,

The title of editing widgets is altered with weird prefixes such as "row::" or "col::" when editing a Data Table.
The end content isn't changed but it confuses clients :

<img width="326" alt="eae_datatable_bug" src="https://user-images.githubusercontent.com/105289691/185913844-f6cf05eb-b6b9-485a-8976-c1b82eecafb0.png">

Wordpress 6.0.1
Elementor 3.7.2
EAE 5.2.3

Thanks

**Comment by nxmndr** [comment]
I just upgraded these 3 components and it's unrelated since it was present before.

**Comment by robinwpdeveloper** [comment]
Hi @nxmndr
Are you still having the mentioned issue (with the latest version)?

Let us know.
Thank you.

**Comment by nxmndr** [comment]
Yes, still present. The text is concatenated to the normal title inside each `div.elementor-repeater-row-item-title`.

Wordpress 6.1.1
Elementor 3.11.2
EAE 5.6.0

**Comment by sadmansakibnadvi** [comment]
Hello @nxmndr ,

Greetings.

Thank you for reaching out to us regarding the technical issue you have encountered on your website. In order for us to provide you with the best possible solution, we would like to gain a deeper understanding of the problem by performing a thorough analysis of your website.

Please note that as this is a public repository, we kindly ask that you refrain from sharing any private information here. Instead, we would appreciate it if you could create a support ticket and provide us with temporary login access so that our technical support team can investigate the issue directly from your end.

To create a support ticket, please follow the link provided below: https://wpdeveloper.com/new-ticket/. Once you have created the ticket, please provide us with the necessary login credentials and any other relevant details related to the issue you are experiencing.

Our technical support team will prioritize your ticket and work diligently to provide you with a prompt resolution to the issue you are experiencing. We appreciate your cooperation in this matter and are committed to providing you with the best possible customer experience.

We look forward to resolving this issue for you. Thank you.
