### ISSUE TITLE
Sticky Video bug when resizing the window

### ISSUE THREAD

**Issue by Mehdi-JAWAD** [WPDevelopers/essential-addons-for-elementor-lite#738]
Resizing the page when using sticky video distorts the video player.

The problem is also on your demo site, to reproduce the problem you just have to

1- Launch the video
2- Scroll down until the mini player appears
3- Resize the window (reduce the width)
4- Scroll up to the video player and you will find it with an incorrect size.

https://essential-addons.com/elementor/sticky-video/

**Comment by onlykawshar** [comment]
Hello @Mehdi-JAWAD, 

I hope you are doing well. 

I have also checked this as you said. Do you think, it has any usecase? Or Can you please provide a screencast? So that I can understand how you are facing this issue. 

Thank you

**Comment by Mehdi-JAWAD** [comment]
Hi @onlykawshar,

Please find below a screencast of the issue:

![2022-09-07_19-32-58](https://user-images.githubusercontent.com/58173459/188942978-6d741955-1d25-4787-95ea-2dea5ee00191.gif)

Best regards,

**Comment by Mehdi-JAWAD** [comment]
Hi @onlykawshar,

Is there any updates about the issue?

**Comment by onlykawshar** [comment]
Hello @Mehdi-JAWAD, 

I hope you are doing well. 

I have talked with our Team about the issue that you raised. But I am so sorry that we can't find any use case here. Because nobody will browse a webpage in a responsive mood from a computer. Also, I couldn't get this issue in a specific responsive mood, It only appears when you will frequently change the responsive mood. I hope you understand. 

Thank you!

**Comment by robinwpdeveloper** [comment]
Closing this issue. Feel free to comment if you find the issue on any real device.
