### ISSUE TITLE
Unable to open items in Elementor Pro's LoopGrid when using EA Wrapper Link

### ISSUE THREAD

**Issue by jura84** [WPDevelopers/essential-addons-for-elementor-lite#763]
Unable to open items in Elementor Pro's LoopGrid when using Essential Addons Wrapper Link with version 6.0.1 or 6.02.
I need to use version 6.0.0 to make sure Wrapper Links works OK.

When using 6.0.2 this issue happens on Edge and Chrome browsers.

Wordpress version: 6.6.1
Elementor Pro version: 3.23.3

**Comment by amin-abir** [comment]
Hi jura84

I hope you are fine.

Sorry for your experience, our team is already concerned about this issue and they are working on it. 
I will inform you once the issue is fixed.

Thanks

**Comment by amin-abir** [comment]
Hi @jura84 

Our dev team has already fixed the issue. Please download the dev version from here, and replace your free plugin with it.
Free plugin: https://d.pr/f/1JriRf

We have checked and its working fine. Please clear your site caches while checking. 

Let me know how its going.

Thanks

**Comment by jura84** [comment]
@amin-abir , I apologize, I did not have a time to test dev version.
At least this is not working with latest version 6.0.4.
I had to revert to 6.0.0.

Any comments?

**Comment by amin-abir** [comment]
Hi Jura84

I hope you are fine.

Actually, the wrapper link issue is fixed in the latest version of Essential Addons, v6.0.4
I just checked on my side with the latest version of the plugin both in Chrome and Edge browser, and its working fine, please check the screencast, https://d.pr/v/DQ0QNJ
The issues that you are facing could be due to caching, so, please clear your site and browser caches. 

Let me know how its going.

Thanks
