### ISSUE TITLE
Recreated - Unable to open items in Elementor Pro's LoopGrid when using EA Wrapper Link

### ISSUE THREAD

**Issue by jura84** [WPDevelopers/essential-addons-for-elementor-lite#766]
Rereport of an old issue which occurs again.

Unable to open items in Elementor Pro's LoopGrid when using Essential Addons Wrapper Link with version 6.0.4.
I need to use version 6.0.0 to make sure Wrapper Links works OK.

When using 6.0.4 this issue happens on Edge and Chrome browsers.

Wordpress version: 6.6.2
Elementor version: 3.23.4
Elementor Pro version: 3.23.3

**Link to the closed issue:**
https://github.com/WPDevelopers/essential-addons-for-elementor-lite/issues/763

**Comment by amin-abir** [comment]
Hi Jura84

I hope you are fine.

Actually, the wrapper link issue is fixed in the latest version of Essential Addons, **v6.0.4**
I just checked on my side with the latest version of the plugin both in Chrome and Edge browser, and its working fine, please check the screencast, https://d.pr/v/DQ0QNJ
The issues that you are facing could be due to caching, so, please clear your site and browser caches. 

Let me know how its going.

Thanks

**Comment by jura84** [comment]
Thanks for your reply.

Almost fixed. :relaxed:
Works on Edge, not on Chrome.

Edge version: 128.0.2739.67 (Official build) (64-bit)
Chrome version: Version 128.0.6613.138 (Official Build) (64-bit)
